--- # Elasticsearch Upgrade Node
- hosts: pns-01
  vars:
    elsDownloadURL: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.1.deb
    elsSHA1: f2fdf6d2bdd6e526c5be53f859c4dd111677a4b6
  become: true
  become_user: root
  become_method: sudo
  # environment:
  #   http_proxy: http://10.13.4.50:3128
  #   https_proxy: http://10.13.4.50:3128
  tasks:
  - name: Stop els Node
    service:
      name: elasticsearch
      state: stopped

  - name: Download Elasticsearch
    get_url:
      url: "{{ elsDownloadURL }}"
      dest: /tmp/els.deb
      checksum: "sha1:{{ elsSHA1 }}"

  - name: Install Elasticsearch
    apt: deb=/tmp/els.deb

  - name: Remove temporary elasticsearch package file
    file: path=/tmp/els.deb state=absent

  # Insert plugin upgrade if necessary

  - name: Restart els Node
    service:
      name: elasticsearch
      state: restarted
      enabled: yes
