---
# tasks file for elasticserver
# - name: Import Elastic GPG Key
#   apt_key: url=http://packages.elastic.co/GPG-KEY-elasticsearch state=present
#
# - name: Add Elastic Repo into source list
#   apt_repository:
#     repo: 'deb http://packages.elastic.co/elasticsearch/{{ elasticsearch_repo_version }}/debian stable main'
#     state: present
#     update_cache: yes
#
# - name: Install Elasticsearch
#   apt: name=elasticsearch state=present update_cache=yes
#   notify: restartELS

- name: Download Elasticsearch
  get_url:
    url: "{{ elsDownloadURL }}"
    dest: /tmp/els.deb
    checksum: "sha1:{{ elsSHA1 }}"

- name: Install Elasticsearch
  apt: deb=/tmp/els.deb

#- include: plugins.yml

- name: Change /etc/sysctl.conf
  blockinfile:
    dest: /etc/sysctl.conf
    block: |
      # hybrid mmapfs / niofs
      vm.max_map_count=262144
      # Use RAM and avoid swap
      vm.swappiness=1
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  notify: restartELS

- name: Install configuration for jvm options
  template: src=jvm.options.j2 dest=/etc/elasticsearch/jvm.options owner=root group=elasticsearch mode=750
  notify: restartELS

- name: Create systemd override directory for ELS service
  file: path=/etc/systemd/system/elasticsearch.service.d state=directory owner=root group=root mode=755

- name: Override elasticsearch systemd configuration
  template: src=elasticsearchSystemd.conf.j2 dest=/etc/systemd/system/elasticsearch.service.d/elasticsearch.conf owner=root group=elasticsearch mode=644
  notify: restartELS

- name: Install configuration file for els front
  template: src=elasticsearch-front.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=elasticsearch mode=750
  notify: restartELS
  when: ansible_hostname == "bb-front-els-pp"

- name: Install configuration file for els-1
  template: src=elasticsearch-1.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=elasticsearch mode=750
  notify: restartELS
  when: ansible_hostname == "bb-back-els1-pp"

- name: Install configuration file for els-2
  template: src=elasticsearch-2.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=elasticsearch mode=750
  notify: restartELS
  when: ansible_hostname == "bb-back-els2-pp"

- name: Install configuration file for els-3
  template: src=elasticsearch-3.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=elasticsearch mode=750
  notify: restartELS
  when: ansible_hostname == "bb-back-els3-pp"
