---
# tasks file for kibana
- name: Download Kibana
  get_url:
    url: "{{ kibanaDownloadURL }}"
    dest: /tmp/kibana.deb
    checksum: "sha1:{{ kibanaSHA1 }}"

- name: Install Elasticsearch
  apt: deb=/tmp/kibana.deb
  notify: restartKibana

- name: Install configuration
  template: src=kibana.yml.j2 dest=/etc/kibana/kibana.yml owner=root group=root mode=644
  notify: restartKibana
