--- # tasks file for javajdk
- name: Check if JDK is already installed
  shell: "if [ -d '/opt/jdk1.8.0_112' ]; then echo true; else echo false; fi"
  register: isInstalled

- name: Debug
  debug:
    msg: "JDK is installed?: {{ isInstalled.stdout }}"

- name: Download JDK
  get_url:
    url: "{{ jdkDownloadURL }}"
    dest: /tmp/{{ jdkName }}.tar.gz
    headers: 'Cookie: oraclelicense=accept-securebackup-cookie'
  when: isInstalled.stdout == "false"

- name: Extract archive
  shell: "tar xzf /tmp/{{ jdkName }}.tar.gz"
  args:
    chdir: /opt
  when: isInstalled.stdout == "false"

- name: Remove temporary jdk archive
  file: path=/tmp/{{ jdkName }}.tar.gz state=absent
  when: isInstalled.stdout == "false"

- name: Set JDK
  shell: "update-alternatives --install /usr/bin/java java /opt/jdk1.8.0_112/bin/java {{ jdkPriority }}; update-alternatives --install /usr/bin/javac javac /opt/jdk1.8.0_112/bin/javac  {{ jdkPriority }}"
  when: isInstalled.stdout == "false"
