---
# vars file for elasticserver
# Package
elsDownloadURL: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.1.deb
elsSHA1: f2fdf6d2bdd6e526c5be53f859c4dd111677a4b6
# Global configuration
elsHeapSize: "4g"
# Configuration
clusterName: agilepartner
splitBrainCount: 2
